namespace UI
{
    public interface IMenu
    {

        /// <summary>
        /// generated by C# XML for Documentation
        /// Will display the menu and user choices in the terminal
        /// </summary>
        void Display();

        /// <summary>
        /// Will record user's choice and change/route your menu based on that choice
        /// </summary>
        /// <returns>Returns the menu that will change user's screen</returns>
        string UserChoice();
    }
}